/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mybatis.sscce.foreach.with.bind;

import java.io.InputStream;
import java.util.List;
import org.apache.ibatis.io.Resources;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;

public class App {
    public static void main(String[] args) throws Exception {
        String resource = "mybatis-config.xml";
        InputStream inputStream = Resources.getResourceAsStream(resource);
        SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);

        try (SqlSession session = sqlSessionFactory.openSession()) {
            Integer result = session.getMapper(FooMapper.class).countBar(List.of(new BarId("test001"), new BarId("test002")));
            System.out.println(result);
        }
    }
}
